label ch1:
    $ skip_next = "skip_to_ch2"
    scene black
    show bg bg2 with Dissolve(2)
    show me nrm at left
    with dissolve
    show jaf nrm at right
    with dissolve
    jaf "Ah, my beloved Agrabah."
    jaf "What's this smell? Crazy Hakim?"
    me "No, it's from all the garbage in the alleys."
    me "They say that you betrayed the Sultan. They say you returned and tried to kill him."
    me "But things were better when you were in charge."
    me "After you 'left', everyone stopped doing their jobs."
    jaf "What else do they say about me?"
    me "That they destroyed you by destroying your lamp."
    jaf "Ah, that. They tried, but turns out Genies can't die."
    jaf "After a painful while, my lamp just appeared where you found me."
    jaf "Where the Cave of Wonders was."
    me "Cave of wonders?"
    jaf "You don't know much about what happened, do you?"
    me "I was there when the Genie picked up the palace and put in on the hilltop."
    me "They said you commanded him."
    me "And I've heard some things from the palace guards here and there."
    me "Usually everything happens inside the palace walls when nobody is around."
    jaf "Interesting. you should tell me those stories at some point."
    jaf "Is the Sultan still alive?"
    me "Yes, the Sultan retired and gave the throne to Aladdin and Jasmine."
    me "He's the new sultan that is always out of the city flying his carpet."
    jaf "And Jasmine have no clue how to rule. I knew it."
    jaf "I'll deal with this later, for now we have a bigger fish to catch."
    me "..."
    jaf "What?"
    me "My fish business..."
    jaf "Snap out of it. Abdul. A whole new life is in front of you."
    jaf "First we need to deal with our first problem, we can't be seen like this."
    jaf "Let's go to your house.{w=.5} This way?"
    me "No."
    jaf "Ah, You've changed your home? This way?"
    me "No."
    jaf "Which way then?"
    me "No way."
    jaf "You've lost your house too?"
    me "Yes, I've been living on the streets."
    jaf "How unfortunate, but lucky for you, I know a place, and I'm sure it's vacant too."
    jaf "Its resident moved to a bigger place."
    jaf "Follow me."
    jump ch2