label chitchat_1:
    me "Jafar, were you smart when you were a child?"
    jaf "I don't think so. I was an ordinary kid, my dad was smart enough to educate me."
    me "So if my dad was smart I would be smart as well?"
    jaf "Smart is simply educated. There's not that much of different between people at birth."
    jaf "Feed a child well and the child grows big and strong. Feed them knowledge and they become smart."
    me "I spent years of my childhood in Maktab, why didn't I became educated?"
    jaf "You were forced to learn, and I bet you hated every moment of it."
    me "I did."
    jaf "My father taught me how to learn, he instilled in me a love of learning."
    jaf "And I never stopped seeking knowledge."
    me "A good man."
    jaf "Yeah, he was."
    return

label chitchat_2:
    me "Jafar, my first wish was about the lamp, how come you can disappear too?"
    jaf "I guess I'm a part of the lamp as well, any wish affecting the lamp affects me as well."
    jaf "I am new to this whole Genie in the Lamp concept. There's many a thing even I don't know yet."
    me "Would a wish affect me as well if I'm in the lamp?"
    jaf "Hmmm... That's a good question. I'll have to test that at some point."
    me "Spare me Jafar, that sounds dangerous."
    jaf "Hah, you're no fun Abdul. "
    return

label chitchat_3:
    me "Were you sucked into the lamp like Aladdin says?"
    jaf "Yes, though the smaller hole."
    me "how did it feel?"
    jaf "As if my whole being was compressed into a tiny dot, then expanded once I was here.
    me "Must've been one of the worst things in the world. "
    jaf "Yes. That's why you are helping me with my revenge. I'll make him experience every single suffering he caused me tenfold."
    return

label chitchat_4:
    me "Jafar, when I leave the lamp, why do I always return exactly where I was? And why does it seem like time haven't moved at all?"
    jaf "I made the time in the lamp move slower than in the outside. A year here is a mere second there."
    jaf "This way, if you enter the lamp when people are looking at you, they wouldn't notice anything out of ordinary."
    jaf "It would be extremely troublesome if you were to blink out of existence for hours at a time, yes?"
    me "I guess you're right, Jafar. But wouldn't I age normally when inside of the lamp?"
    jaf "You put less faith in me than I thought, Abdul. Trust me, you can spend many millenia in the lamp and not grow a single day old."
    jaf "I don't want my trusty pawn dying before we achieve what we want."
    return

label chitchat_5:
    me "How far can I wander in this darkness?"
    jaf "You can run in any direction for thousands and thousands of years and still see nothing but darkness."
    jaf "But beyond that is a whole world, unlike ours. Filled with wonders you can't even imagine."
    jaf "I think this world is the product of the dreams of the people on the outside. There's the only explanation I could come up with."
    jaf "Somewhere beyond those stars is a world like this, with seas, lands and cities thousands of times bigger than Agrabah."
    jaf "Crawling with not only people but fantastical creatures."
    jaf "Tools of extreme complexity, wonders of engineering and technology."
    jaf "Perhaps I will show you that place when this is all over."
    me "Well, I wouldn't mind having you showing me the world. I bet it's shining, shimm-"
    jaf "Don't say another word."
    return

label chitchat_6:
    me "Jafar, where did the rules of lamp came from?"
    jaf "I don't know, they seem arbitrary."
    jaf "Probably made by the being who created the lamps in the first place."
    jaf "Made to both protect the people of the outside and control the immense power that Genies have."
    me "They're probably both brilliant and cruel."
    jaf "Yes. I know that firsthand."
    return

label chitchat_7:
    me "Why do you write books, Jafar?"
    jaf "Because that's the purpose of life."
    me "Writing books?"
    jaf "Not writing books per se. Passing information to the next generations."
    jaf "Writing books is just a mean of fulfilling that purpose."
    me "Don't you mean it the purpose of YOUR life?"
    jaf "No. {w=.5} All life, big and small."
    me "But animals can't write books!"
    jaf "Alkh... alright, let me educate you."
    jaf "How long a dog lives around here?"
    me "Five, maybe seven years?"
    jaf "They don't live forever do they?"
    me "No."
    jaf "How come there are still dogs around? We have lived longer than seven years."
    me "Dogs breed, Jafar. Those are new dogs."
    jaf "Are they? They look like the same dogs I've seen when I was a kid."
    me "Most dogs look like their parents when they grow up."
    jaf "Exactly!"
    jaf "The number of legs, the color of fur, the size and many other attributes are passed on from one generation to the next."
    jaf "And not just from the mother, they look like their fathers too."
    jaf "I can only assume when the dogs mate, some instruction of the males attributes are transferred to the females womb."
    jaf "And that's how the new dogs are made."
    me "But..."
    jaf "Can't you see? All they are doing is transferring the information that made them, to their offsprings."
    jaf "And isn't that the ultimate purpose of life?"
    jaf "Preserving the information that makes us in the cycles of birth and death?"
    me "But what does that have to do with writhing books?"
    jaf "Patience my friend. I'm not finished yet."
    jaf "Where you born a fish vendor?"
    me "No I learned it from my father."
    jaf "I know it's not the best example since most of us inherit our fathers businesses."
    jaf "Carpenter from carpenter, farmer from farmer and sultan from sultan."
    jaf "But we know: Trained in another profession, a child become something unlike the parents."
    jaf "The information we learn after birth are transfered to our offspring through teaching."
    jaf "A book is simply another means of transferring our experiences to the next generations."
    jaf "I'm not sure if I even have the ability to sire children anymore, but anybody who reads my books will inherit some of me."
    me "..."
    jaf "What's the matter?"
    me "Nothing, I just don't know how to feel about it."
    jaf "Feel however you want, but do it somewhere else, I'm not interested in your feelings."
    return

label chitchat_8:
    me "What do you think about xxx."
    jaf "xxx is a big sack of shit."
    me "xxx can't help it, xxx gains weight even if xxx drinks water."
    jaf "That's a lie."
    me "How do you know?"
    jaf "Imagine a sack of shit."
    me "What?"
    jaf "Just imagine."
    jaf "A sack of shit with a hole at the bottom."
    me "That's crude."
    jaf "..."
    jaf "If you start stuffing it from the top, more than comes out from the hole, it gets bigger."
    jaf "If you pour water in it, the shit soaks up some of the water, but eventually it becomes saturated."
    jaf "The exes water starts to drip from every nook and cranny."
    me "xxx looks like xxx 's filled with liquid."
    jaf "Indeed. but I doubt it can be pure water. there most be lots of shit mixed in xxx"
    me "So the only way to lose weight is shitting more than we eat?"
    jaf "I don't think so, I did some experiments weighing what I eat and what I shit."
    jaf "It doesn't seem we shit anything close to how much as we eat."
    jaf "Shit, piss, sweat and breath. those are the only things that come out of humans."
    jaf "I can only assume: whatever we eat becomes a part of those to come out."
    me "But we breath out the same air we breath in, that can't have food in it."
    jaf "To the contrary, that's my main suspect. but I need to do some experiments to make sure."
    me "Leave me out of your weird experiments will you?"
    jaf "Sure, sure..."
    return

label chitchat_9:
    me "Jafar, what did you mean when you said you're not sure about heaven?"
    me "I've been good. Did all of my prayers. I should go to heaven right?"
    jaf "It's a scam. Give up your possessions and you'll be rewarded when you're dead."
    jaf "Don't be stupid, follow the money. See who is benefiting from this."
    me "Malik and Hosein?"
    jaf "Exactly, have you seen either of them work?"
    me "Not really."
    jaf "Yet they can afford marvelous houses, expensive clothing and food. Whose money are they spending?"
    me "emmm..."
    jaf "Yours, you idiot. They are spending people's charity money."
    jaf "They're not feeding the hungry. They're not helping the poor. They're filling their pockets."
    me "They're abusing people's beliefs. They'll go to hell."
    jaf "Well, if it existed in the first place."
    me "But they should pay for their sins."
    jaf "I agree..."
    me "How is that fair if they don't suffer in hell?"
    jaf "The world doesn't care about fairness, we do."
    jaf "If you want fairness you'll have to create it yourself."
    me "I'll do it. I'll create fairness by myself."
    return

label chitchat_10:
    me "Jafar, How did Aladdin find his lamp?"
    jaf "He snatched it from my hands."
    jaf "I've spent years looking for it, and I was ready to pay any price."
    jaf "Even killing a human."
    me "Huh..."
    jaf "What's the matter?"
    me "It feels wierd hearing you talk about killing people."
    me "I never seen you at any execution when you were the vizier."
    jaf "Yeah, I always avoided killing as much as I could. I had many chances to kill Aladdin but I always hesitated."
    jaf "The situation I'm in now is all the result of my subconscious' hesitation."
    me "I figured you're not the killing type. It's not hard to hire one of Asasiyyun to kill him."
    jaf "Yes, I had plenty of time thinking about that, but it's all in the past, now. Let's focus to the task at hand."
    return

label chitchat_11:
    "(jafar's golden rule: reciprocity)"
